### ISSUE TITLE
I ran the deploy script, but bootstrapping was with failure with message below. I have tried to delete the CDKToolKit stack from Cloudfomation, remove "cdk" buckets from S3, but it still could not fix the issue. Pleas he

### ISSUE THREAD

**Issue by JianYan-g** [aws-samples/nvidia-omniverse-nucleus-on-amazon-ec2#1]
⏳  Bootstrapping environment aws://xxxxxxxxxx/us-west-2...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkit: creating CloudFormation changeset...
12:28:32 PM | CREATE_FAILED        | AWS::IAM::Policy      | ImagePublishingRoleDefaultPolicy
Unable to retrieve Arn attribute for AWS::ECR::Repository, with error message null

 ❌  Environment aws://xxxxxxxxxxx/us-west-2 failed bootstrapping: Error: The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Unable to retrie
ve Arn attribute for AWS::ECR::Repository, with error message null
    at FullCloudFormationDeployment.monitorDeployment (/home/ssm-user/.nvm/versions/node/v16.17.1/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:496:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /home/ssm-user/.nvm/versions/node/v16.17.1/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:626:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (/home/ssm-user/.nvm/versions/node/v16.17.1/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:623:5)
    at initCommandLine (/home/ssm-user/.nvm/versions/node/v16.17.1/lib/node_modules/aws-cdk/lib/cli.ts:357:12)

The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Unable to retrieve Arn attribute for AWS::ECR::Repository, with error message null

**Comment by kellan-cartledge** [comment]
Hi @JianYan-g, since this application was built with AWS CDK, it expects your AWS environment to be set in your CLI, by default, or for your environment to be configured in `omni-app.ts`. See line 64: `env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: process.env.CDK_DEFAULT_REGION }`

To try deploying this application again, please, first delete any stacks related to this project from CloudFormation in your account. Then either set your environment in your CLI with the AWS CLI or hard-coded in `omni-app.ts`. Then run `./deploy.sh`. The deploy script will bootstrap the AWS CDK toolkit in the account and region you have specified and then deploy the application there.

Please see this documentation to learn more about how AWS CDK works with environments: [https://docs.aws.amazon.com/cdk/v2/guide/environments.html](https://docs.aws.amazon.com/cdk/v2/guide/environments.html)
